# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Checkout_window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 542)
        MainWindow.setStyleSheet("background-color: rgb(247, 255, 240)\n""")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pay_button = QtWidgets.QPushButton(self.centralwidget)
        self.pay_button.setGeometry(QtCore.QRect(130, 380, 131, 51))
        self.pay_button.setStyleSheet("background-color: rgb(132, 255, 94);")
        self.pay_button.setObjectName("pay_button")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(230, 130, 100, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.comboBox.setObjectName("comboBox")
        self.Items_label = QtWidgets.QLabel(self.centralwidget)
        self.Items_label.setGeometry(QtCore.QRect(80, 120, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Items_label.setFont(font)
        self.Items_label.setObjectName("Items_label")
        self.Total_price_label = QtWidgets.QLabel(self.centralwidget)
        self.Total_price_label.setGeometry(QtCore.QRect(80, 230, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Total_price_label.setFont(font)
        self.Total_price_label.setObjectName("Total_price_label")
        self.total_price_text = QtWidgets.QLabel(self.centralwidget)
        self.total_price_text.setGeometry(QtCore.QRect(260, 240, 71, 16))
        self.total_price_text.setObjectName("total_price_text")
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        self.main_label.setGeometry(QtCore.QRect(160, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main_label.setFont(font)
        self.main_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_label.setObjectName("main_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pay_button.setText(_translate("MainWindow", "Pay"))
        self.Items_label.setText(_translate("MainWindow", "Items purchased"))
        self.Total_price_label.setText(_translate("MainWindow", "Total price: "))
        self.total_price_text.setText(_translate("MainWindow", "0"))
        self.main_label.setText(_translate("MainWindow", "Checkout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Checkout_window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
