# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Registration_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(382, 497)
        MainWindow.setStyleSheet("background-color:rgb(248, 255, 239)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.proceed_button = QtWidgets.QPushButton(self.centralwidget)
        self.proceed_button.setGeometry(QtCore.QRect(130, 320, 131, 51))
        self.proceed_button.setStyleSheet("background-color: rgb(101, 255, 111);")
        self.proceed_button.setObjectName("proceed_button")
        self.name_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.name_entry.setGeometry(QtCore.QRect(100, 100, 191, 21))
        self.name_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_entry.setText("")
        self.name_entry.setObjectName("name_entry")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 100, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 47, 13))
        self.label_2.setObjectName("label_2")
        self.email_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.email_entry.setGeometry(QtCore.QRect(100, 150, 191, 21))
        self.email_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email_entry.setText("")
        self.email_entry.setObjectName("email_entry")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 200, 71, 16))
        self.label_3.setObjectName("label_3")
        self.password_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.password_entry.setGeometry(QtCore.QRect(100, 200, 191, 21))
        self.password_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_entry.setText("")
        self.password_entry.setObjectName("password_entry")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 20, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.age_check = QtWidgets.QCheckBox(self.centralwidget)
        self.age_check.setGeometry(QtCore.QRect(130, 270, 141, 17))
        self.age_check.setObjectName("age_check")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 382, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.proceed_button.setText(_translate("MainWindow", "Proceed"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Email:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.label_4.setText(_translate("MainWindow", "GREAT BUY"))
        self.age_check.setText(_translate("MainWindow", "Over 15 years of age"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Registration_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
