# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ViewItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class View_Item_UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 553)
        MainWindow.setStyleSheet("background-color:rgb(247, 255, 240)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 351, 321))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.Image = QtWidgets.QLabel(self.groupBox)
        self.Image.setGeometry(QtCore.QRect(110, 140, 141, 51))
        self.Image.setObjectName("Image")
        self.label_Name = QtWidgets.QLabel(self.centralwidget)
        self.label_Name.setGeometry(QtCore.QRect(420, 90, 321, 16))
        self.label_Name.setObjectName("label_Name")
        self.label_about = QtWidgets.QLabel(self.centralwidget)
        self.label_about.setGeometry(QtCore.QRect(420, 330, 221, 71))
        self.label_about.setObjectName("label_about")
        self.text_Color = QtWidgets.QLabel(self.centralwidget)
        self.text_Color.setGeometry(QtCore.QRect(420, 130, 91, 16))
        self.text_Color.setObjectName("text_Color")
        self.label_Color = QtWidgets.QLabel(self.centralwidget)
        self.label_Color.setGeometry(QtCore.QRect(560, 130, 141, 16))
        self.label_Color.setObjectName("label_Color")
        self.label_processor = QtWidgets.QLabel(self.centralwidget)
        self.label_processor.setGeometry(QtCore.QRect(560, 180, 141, 16))
        self.label_processor.setObjectName("label_processor")
        self.text_Processor_2 = QtWidgets.QLabel(self.centralwidget)
        self.text_Processor_2.setGeometry(QtCore.QRect(420, 180, 91, 16))
        self.text_Processor_2.setObjectName("text_Processor_2")
        self.label_storage = QtWidgets.QLabel(self.centralwidget)
        self.label_storage.setGeometry(QtCore.QRect(560, 230, 141, 16))
        self.label_storage.setObjectName("label_storage")
        self.text_Type_of_storage = QtWidgets.QLabel(self.centralwidget)
        self.text_Type_of_storage.setGeometry(QtCore.QRect(420, 230, 91, 16))
        self.text_Type_of_storage.setObjectName("text_Type_of_storage")
        self.text_screensize = QtWidgets.QLabel(self.centralwidget)
        self.text_screensize.setGeometry(QtCore.QRect(420, 290, 91, 16))
        self.text_screensize.setObjectName("text_screensize")
        self.label_screensize = QtWidgets.QLabel(self.centralwidget)
        self.label_screensize.setGeometry(QtCore.QRect(560, 290, 141, 16))
        self.label_screensize.setObjectName("label_screensize")
        self.label_price = QtWidgets.QLabel(self.centralwidget)
        self.label_price.setGeometry(QtCore.QRect(20, 450, 141, 51))
        self.label_price.setObjectName("label_price")
        self.button_add_to_cart = QtWidgets.QPushButton(self.centralwidget)
        self.button_add_to_cart.setGeometry(QtCore.QRect(490, 450, 131, 51))
        self.button_add_to_cart.setStyleSheet("background-color:rgb(132, 255, 94)")
        self.button_add_to_cart.setObjectName("button_add_to_cart")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.Image.setText(_translate("MainWindow", "TextLabel"))
        self.label_Name.setText(_translate("MainWindow", "TextLabel"))
        self.label_about.setText(_translate("MainWindow", "TextLabel"))
        self.text_Color.setText(_translate("MainWindow", "Color"))
        self.label_Color.setText(_translate("MainWindow", "TextLabel"))
        self.label_processor.setText(_translate("MainWindow", "TextLabel"))
        self.text_Processor_2.setText(_translate("MainWindow", "Processor"))
        self.label_storage.setText(_translate("MainWindow", "TextLabel"))
        self.text_Type_of_storage.setText(_translate("MainWindow", "Type of storage"))
        self.text_screensize.setText(_translate("MainWindow", "Screen Size"))
        self.label_screensize.setText(_translate("MainWindow", "TextLable"))
        self.label_price.setText(_translate("MainWindow", "TextLabel"))
        self.button_add_to_cart.setText(_translate("MainWindow", "Add to cart"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = View_Item_UI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
