# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifiedVisual.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 749)
        MainWindow.setStyleSheet("background-color:rgb(247, 255, 240)")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 171, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filter_processor = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.filter_processor.setStyleSheet("background-color:rgb(132, 255, 94)")
        self.filter_processor.setObjectName("filter_processor")
        self.Intel_9 = QtWidgets.QRadioButton(self.filter_processor)
        self.Intel_9.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.Intel_9.setObjectName("Intel_9")
        self.Intel_7 = QtWidgets.QRadioButton(self.filter_processor)
        self.Intel_7.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.Intel_7.setObjectName("Intel_7")
        self.Intel_5 = QtWidgets.QRadioButton(self.filter_processor)
        self.Intel_5.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.Intel_5.setObjectName("Intel_5")
        self.Intel_3 = QtWidgets.QRadioButton(self.filter_processor)
        self.Intel_3.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.Intel_3.setObjectName("Intel_3")
        self.AMD9 = QtWidgets.QRadioButton(self.filter_processor)
        self.AMD9.setGeometry(QtCore.QRect(10, 100, 82, 17))
        self.AMD9.setObjectName("AMD9")
        self.AMD7 = QtWidgets.QRadioButton(self.filter_processor)
        self.AMD7.setGeometry(QtCore.QRect(10, 120, 82, 17))
        self.AMD7.setObjectName("AMD7")
        self.AMD5 = QtWidgets.QRadioButton(self.filter_processor)
        self.AMD5.setGeometry(QtCore.QRect(10, 140, 82, 17))
        self.AMD5.setObjectName("AMD5")
        self.verticalLayout.addWidget(self.filter_processor)
        self.shopping_button = QtWidgets.QPushButton(self.centralwidget)
        self.shopping_button.setGeometry(QtCore.QRect(1010, 0, 111, 41))
        self.shopping_button.setStyleSheet("background-color:rgb(132, 255, 94)")
        self.shopping_button.setObjectName("shopping_button")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(10, 0, 75, 23))
        self.login_button.setStyleSheet("background-color:rgb(132, 255, 94)")
        self.login_button.setObjectName("login_button")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 240, 171, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.filter_screensize = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.filter_screensize.setStyleSheet("background-color:rgb(132, 255, 94)")
        self.filter_screensize.setObjectName("filter_screensize")
        self.smallest = QtWidgets.QRadioButton(self.filter_screensize)
        self.smallest.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.smallest.setObjectName("smallest")
        self.lowermid = QtWidgets.QRadioButton(self.filter_screensize)
        self.lowermid.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.lowermid.setObjectName("lowermid")
        self.mid = QtWidgets.QRadioButton(self.filter_screensize)
        self.mid.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.mid.setObjectName("mid")
        self.uppermid = QtWidgets.QRadioButton(self.filter_screensize)
        self.uppermid.setGeometry(QtCore.QRect(10, 80, 101, 17))
        self.uppermid.setObjectName("uppermid")
        self.largest = QtWidgets.QRadioButton(self.filter_screensize)
        self.largest.setGeometry(QtCore.QRect(10, 100, 82, 17))
        self.largest.setObjectName("largest")
        self.verticalLayout_2.addWidget(self.filter_screensize)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 390, 171, 101))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.filter_color_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget_3)
        self.filter_color_2.setStyleSheet("background-color:rgb(132, 255, 94)")
        self.filter_color_2.setObjectName("filter_color_2")
        self.c_black = QtWidgets.QRadioButton(self.filter_color_2)
        self.c_black.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.c_black.setObjectName("c_black")
        self.c_silver = QtWidgets.QRadioButton(self.filter_color_2)
        self.c_silver.setGeometry(QtCore.QRect(10, 40, 91, 17))
        self.c_silver.setObjectName("c_silver")
        self.c_white = QtWidgets.QRadioButton(self.filter_color_2)
        self.c_white.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.c_white.setObjectName("c_white")
        self.c_gray = QtWidgets.QRadioButton(self.filter_color_2)
        self.c_gray.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.c_gray.setObjectName("c_gray")
        self.verticalLayout_3.addWidget(self.filter_color_2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 500, 160, 80))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.filter_storagetype = QtWidgets.QGroupBox(self.verticalLayoutWidget_4)
        self.filter_storagetype.setStyleSheet("background-color:rgb(132, 255, 94)")
        self.filter_storagetype.setObjectName("filter_storagetype")
        self.storage_ssd = QtWidgets.QRadioButton(self.filter_storagetype)
        self.storage_ssd.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.storage_ssd.setObjectName("storage_ssd")
        self.storage_HDD = QtWidgets.QRadioButton(self.filter_storagetype)
        self.storage_HDD.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.storage_HDD.setObjectName("storage_HDD")
        self.verticalLayout_4.addWidget(self.filter_storagetype)
        self.filter_button = QtWidgets.QPushButton(self.centralwidget)
        self.filter_button.setGeometry(QtCore.QRect(10, 590, 75, 23))
        self.filter_button.setStyleSheet("background-color:rgb(132, 255, 94)")
        self.filter_button.setObjectName("filter_button")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(289, 70, 631, 621))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.AllProducts = QtWidgets.QGroupBox(self.verticalLayoutWidget_5)
        self.AllProducts.setTitle("")
        self.AllProducts.setObjectName("AllProducts")        
        self.verticalLayout_5.addWidget(self.AllProducts)
        self.BUTTON_login_in = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTON_login_in.setGeometry(QtCore.QRect(100, 0, 75, 23))
        self.BUTTON_login_in.setStyleSheet("background-color:rgb(132, 255, 94)")
        self.BUTTON_login_in.setObjectName("BUTTON_login_in")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.filter_processor.setTitle(_translate("MainWindow", "Processor"))
        self.Intel_9.setText(_translate("MainWindow", "Intel Core i9"))
        self.Intel_7.setText(_translate("MainWindow", "Intel Core i7"))
        self.Intel_5.setText(_translate("MainWindow", "Intel Core i5"))
        self.Intel_3.setText(_translate("MainWindow", "Intel Core i3"))
        self.AMD9.setText(_translate("MainWindow", "AMD Ryzen 9"))
        self.AMD7.setText(_translate("MainWindow", "AMD Ryzen 7"))
        self.AMD5.setText(_translate("MainWindow", "AMD Ryzen 5"))
        self.shopping_button.setText(_translate("MainWindow", "Finish shopping"))
        self.login_button.setText(_translate("MainWindow", "Register"))
        self.filter_screensize.setTitle(_translate("MainWindow", "Screen size"))
        self.smallest.setText(_translate("MainWindow", "x<11\""))
        self.lowermid.setText(_translate("MainWindow", "11\'\'≥x<14\""))
        self.mid.setText(_translate("MainWindow", "14\"≥x<15.6\""))
        self.uppermid.setText(_translate("MainWindow", "15.6\'\'≥x<17.3\""))
        self.largest.setText(_translate("MainWindow", "x≥17.3\""))
        self.filter_color_2.setTitle(_translate("MainWindow", "Color"))
        self.c_black.setText(_translate("MainWindow", "Black"))
        self.c_silver.setText(_translate("MainWindow", "Silver"))
        self.c_white.setText(_translate("MainWindow", "white"))
        self.c_gray.setText(_translate("MainWindow", "Gray"))
        self.filter_storagetype.setTitle(_translate("MainWindow", "Storage Type"))
        self.storage_ssd.setText(_translate("MainWindow", "SSD"))
        self.storage_HDD.setText(_translate("MainWindow", "HDD"))
        self.filter_button.setText(_translate("MainWindow", "Filter"))

        self.BUTTON_login_in.setText(_translate("MainWindow", "Log in"))
        

    #make a group box is a function that basically creates a whole ITEM
    #group box + labels + button + image
    
    def make_groupbox(self,value_GROUP,value_BUTTON,iteration):
        allelements = []
        allbuttons  = []
        if iteration == 1:
            x = 5
            #150
        else: 
            x = 155 * (iteration-1)
            
        _translate = QtCore.QCoreApplication.translate
        
        #group box
        my_str = value_GROUP + str(iteration)
        self.my_str = QtWidgets.QGroupBox(self.AllProducts)
        self.my_str.setGeometry(QtCore.QRect(10, x, 611, 145))
        self.my_str.setObjectName(my_str)
        self.my_str.setTitle(_translate("MainWindow", my_str))
        
        allelements.append(self.my_str)



        #button
        buttonname = value_BUTTON
        self.buttonname = QtWidgets.QPushButton(self.AllProducts)
        self.buttonname.setGeometry(QtCore.QRect(350, x+100, 75, 31))
        self.buttonname.setObjectName(buttonname)
        self.buttonname.setText(_translate("MainWindow", "cotijebe"))
        
        allelements.append(self.buttonname)
        allbuttons.append(self.buttonname)
        x = x+155
        return allelements 
        
        

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    MainWindow.show()
    sys.exit(app.exec_())
